# Generated by Django 5.1.6 on 2026-03-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingslot',
            name='parking_map',
            field=models.ImageField(blank=True, null=True, upload_to='parking_slots/'),
        ),
    ]
